/**
 * ────────────────────────────────────────────
 *  BOOK CATALOG — The Book Club
 * ────────────────────────────────────────────
 *
 *  HOW TO ADD A NEW BOOK
 *  Simply add a new object to the array below:
 *
 *    { title: "Book Title Here", author: "Author Name Here" },
 *
 *  Save the file and refresh the website. That's it!
 *
 * ────────────────────────────────────────────
 */

const books = [
  { title: "10 Minutes 38 Seconds in This Strange World", author: "Elif Shafak" },
  { title: "11/22/63", author: "Stephen King" },
  { title: "1984", author: "George Orwell" },
  { title: "1Q84", author: "Haruki Murakami" },
  { title: "61 Hours", author: "Lee Child" },
  { title: "A Better Man", author: "Louise Penny" },
  { title: "A Caribbean Mystery", author: "Agatha Christie" },
  { title: "A Court of Frost and Starlight", author: "Sarah J. Maas" },
  { title: "A Court of Mist and Fury", author: "Sarah J. Maas" },
  { title: "A Court of Silver Flames", author: "Sarah J. Maas" },
  { title: "A Court of Thorns and Roses", author: "Sarah J. Maas" },
  { title: "A Court of Wings and Ruin", author: "Sarah J. Maas" },
  { title: "A Crown of Swords", author: "Robert Jordan" },
  { title: "A Darker Shade of Magic", author: "V. E. Schwab" },
  { title: "A Drink Before the War", author: "Dennis Lehane" },
  { title: "A Fatal Grace", author: "Louise Penny" },
  { title: "A Fine Balance", author: "Rohinton Mistry" },
  { title: "A Gambling Man", author: "David Baldacci" },
  { title: "A Gentleman in Moscow", author: "Amor Towles" },
  { title: "A Man Called Ove", author: "Fredrik Backman" },
  { title: "A Memory of Light", author: "Robert Jordan & Brandon Sanderson" },
  { title: "A Tale of Two Cities", author: "Charles Dickens" },
  { title: "A Thousand Splendid Suns", author: "Khaled Hosseini" },
  { title: "A Time to Kill", author: "John Grisham" },
  { title: "A Wanted Man", author: "Lee Child" },
  { title: "A World of Curiosities", author: "Louise Penny" },
  { title: "Absolute Power", author: "David Baldacci" },
  { title: "After Dark", author: "Haruki Murakami" },
  { title: "Alex Cross, Run", author: "James Patterson" },
  { title: "All the Devils Are Here", author: "Louise Penny" },
  { title: "All the Light We Cannot See", author: "Anthony Doerr" },
  { title: "All the Missing Girls", author: "Megan Miranda" },
  { title: "Allegiant", author: "Veronica Roth" },
  { title: "Along Came a Spider", author: "James Patterson" },
  { title: "American Gods", author: "Neil Gaiman" },
  { title: "Americanah", author: "Chimamanda Ngozi Adichie" },
  { title: "And Then There Were None", author: "Agatha Christie" },
  { title: "Angels & Demons", author: "Dan Brown" },
  { title: "Animal Farm", author: "George Orwell" },
  { title: "Anna Karenina", author: "Leo Tolstoy" },
  { title: "Anxious People", author: "Fredrik Backman" },
  { title: "Arc of a Scythe", author: "Neal Shusterman" },
  { title: "As Good As Dead", author: "Holly Jackson" },
  { title: "Assassin's Quest", author: "Robin Hobb" },
  { title: "Atomic Habits", author: "James Clear" },
  { title: "Babel", author: "R. F. Kuang" },
  { title: "Bad Luck and Trouble", author: "Lee Child" },
  { title: "Bag of Bones", author: "Stephen King" },
  { title: "Beach Read", author: "Emily Henry" },
  { title: "Beartown", author: "Fredrik Backman" },
  { title: "Before the Coffee Gets Cold", author: "Toshikazu Kawaguchi" },
  { title: "Before They Are Hanged", author: "Joe Abercrombie" },
  { title: "Before We Say Goodbye", author: "Toshikazu Kawaguchi" },
  { title: "Before Your Memory Fades", author: "Toshikazu Kawaguchi" },
  { title: "Behind Closed Doors", author: "B. A. Paris" },
  { title: "Bel Canto", author: "Ann Patchett" },
  { title: "Best Served Cold", author: "Joe Abercrombie" },
  { title: "Bewilderment", author: "Richard Powers" },
  { title: "Big Little Lies", author: "Liane Moriarty" },
  { title: "Big Summer", author: "Jennifer Weiner" },
  { title: "Billy Summers", author: "Stephen King" },
  { title: "Black Cake", author: "Charmaine Wilkerson" },
  { title: "Bleachers", author: "John Grisham" },
  { title: "Blood Work", author: "Michael Connelly" },
  { title: "Bloodmarked", author: "Tracy Deonn" },
  { title: "Blue Lily, Lily Blue", author: "Maggie Stiefvater" },
  { title: "Blue Moon", author: "Lee Child" },
  { title: "Book Lovers", author: "Emily Henry" },
  { title: "Book of Night", author: "Holly Black" },
  { title: "Brave New World", author: "Aldous Huxley" },
  { title: "Bride", author: "Ali Hazelwood" },
  { title: "Bring Me Back", author: "B. A. Paris" },
  { title: "Broken Harbor", author: "Tana French" },
  { title: "Brother Odd", author: "Dean Koontz" },
  { title: "Bury Your Dead", author: "Louise Penny" },
  { title: "Caraval", author: "Stephanie Garber" },
  { title: "Cards on the Table", author: "Agatha Christie" },
  { title: "Career of Evil", author: "Robert Galbraith" },
  { title: "Carrie Soto Is Back", author: "Taylor Jenkins Reid" },
  { title: "Carrion Comfort", author: "Dan Simmons" },
  { title: "Cat and Mouse", author: "James Patterson" },
  { title: "Catching Fire", author: "Suzanne Collins" },
  { title: "Caught", author: "Harlan Coben" },
  { title: "Chain of Gold", author: "Cassandra Clare" },
  { title: "Chain of Iron", author: "Cassandra Clare" },
  { title: "Chain of Thorns", author: "Cassandra Clare" },
  { title: "Champion", author: "Marie Lu" },
  { title: "Children of Ruin", author: "Adrian Tchaikovsky" },
  { title: "Children of Time", author: "Adrian Tchaikovsky" },
  { title: "Circe", author: "Madeline Miller" },
  { title: "City of Ashes", author: "Cassandra Clare" },
  { title: "City of Bones", author: "Cassandra Clare" },
  { title: "City of Glass", author: "Cassandra Clare" },
  { title: "Clockwork Angel", author: "Cassandra Clare" },
  { title: "Clockwork Prince", author: "Cassandra Clare" },
  { title: "Clockwork Princess", author: "Cassandra Clare" },
  { title: "Cloud Atlas", author: "David Mitchell" },
  { title: "Cloud Cuckoo Land", author: "Anthony Doerr" },
  { title: "Cold Fire", author: "Dean Koontz" },
  { title: "Colorless Tsukuru Tazaki and His Years of Pilgrimage", author: "Haruki Murakami" },
  { title: "Commonwealth", author: "Ann Patchett" },
  { title: "Convenience Store Woman", author: "Sayaka Murata" },
  { title: "Coraline", author: "Neil Gaiman" },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
  { title: "Crook Manifesto", author: "Colson Whitehead" },
  { title: "Crooked House", author: "Agatha Christie" },
  { title: "Crooked Kingdom", author: "Leigh Bardugo" },
  { title: "Cross", author: "James Patterson" },
  { title: "Cross Country", author: "James Patterson" },
  { title: "Crossroads of Twilight", author: "Robert Jordan" },
  { title: "Crown of Midnight", author: "Sarah J. Maas" },
  { title: "Curtain", author: "Agatha Christie" },
  { title: "Daisy Darker", author: "Alice Feeney" },
  { title: "Daisy Jones & The Six", author: "Taylor Jenkins Reid" },
  { title: "Dance Dance Dance", author: "Haruki Murakami" },
  { title: "Dark Corners", author: "Megan Goldin" },
  { title: "Dark Places", author: "Gillian Flynn" },
  { title: "Dark Rivers of the Heart", author: "Dean Koontz" },
  { title: "Darling Girls", author: "Sally Hepworth" },
  { title: "Dear Edward", author: "Ann Napolitano" },
  { title: "Dear Wife", author: "Kimberly Belle" },
  { title: "Death on the Nile", author: "Agatha Christie" },
  { title: "Deep Work", author: "Cal Newport" },
  { title: "Defy Me", author: "Tahereh Mafi" },
  { title: "Demon Copperhead", author: "Barbara Kingsolver" },
  { title: "Die Trying", author: "Lee Child" },
  { title: "Divergent", author: "Veronica Roth" },
  { title: "Divine Justice", author: "David Baldacci" },
  { title: "Do Not Disturb", author: "Freida McFadden" },
  { title: "Doctor Sleep", author: "Stephen King" },
  { title: "Don Quixote", author: "Miguel de Cervantes" },
  { title: "Don't Let Go", author: "Harlan Coben" },
  { title: "Dracula", author: "Bram Stoker" },
  { title: "Dragon Tears", author: "Dean Koontz" },
  { title: "Drive Your Plow Over the Bones of the Dead", author: "Olga Tokarczuk" },
  { title: "Dune", author: "Frank Herbert" },
  { title: "East of Eden", author: "John Steinbeck" },
  { title: "Earthlings", author: "Sayaka Murata" },
  { title: "Echo Burning", author: "Lee Child" },
  { title: "Eight Hundred Grapes", author: "Laura Dave" },
  { title: "Elantris", author: "Brandon Sanderson" },
  { title: "Elder Race", author: "Adrian Tchaikovsky" },
  { title: "Emma", author: "Jane Austen" },
  { title: "Empire of Storms", author: "Sarah J. Maas" },
  { title: "End of Watch", author: "Stephen King" },
  { title: "Equal Rites", author: "Terry Pratchett" },
  { title: "Everything I Never Told You", author: "Celeste Ng" },
  { title: "Evil Under the Sun", author: "Agatha Christie" },
  { title: "Exiles", author: "Jane Harper" },
  { title: "Fahrenheit 451", author: "Ray Bradbury" },
  { title: "Fair Warning", author: "Michael Connelly" },
  { title: "Fairy Tale", author: "Stephen King" },
  { title: "Faithful Place", author: "Tana French" },
  { title: "False Memory", author: "Dean Koontz" },
  { title: "Finale", author: "Stephanie Garber" },
  { title: "Final Girls", author: "Riley Sager" },
  { title: "Finders Keepers", author: "Stephen King" },
  { title: "Firefly Lane", author: "Kristin Hannah" },
  { title: "Five Little Pigs", author: "Agatha Christie" },
  { title: "Five Survive", author: "Holly Jackson" },
  { title: "Flights", author: "Olga Tokarczuk" },
  { title: "Flood of Fire", author: "Amitav Ghosh" },
  { title: "Fool Me Once", author: "Harlan Coben" },
  { title: "Force of Nature", author: "Jane Harper" },
  { title: "Forever Odd", author: "Dean Koontz" },
  { title: "Fourth Wing", author: "Rebecca Yarros" },
  { title: "Frankenstein", author: "Mary Shelley" },
  { title: "From the Corner of His Eye", author: "Dean Koontz" },
  { title: "Funny Story", author: "Emily Henry" },
  { title: "Glass Houses", author: "Louise Penny" },
  { title: "Glass Sword", author: "Victoria Aveyard" },
  { title: "Gods of Jade and Shadow", author: "Silvia Moreno-Garcia" },
  { title: "Gone Girl", author: "Gillian Flynn" },
  { title: "Gone Tomorrow", author: "Lee Child" },
  { title: "Gone for Good", author: "Harlan Coben" },
  { title: "Gone, Baby, Gone", author: "Dennis Lehane" },
  { title: "Good Girl, Bad Blood", author: "Holly Jackson" },
  { title: "Good Omens", author: "Neil Gaiman & Terry Pratchett" },
  { title: "Gray Mountain", author: "John Grisham" },
  { title: "Great Expectations", author: "Charles Dickens" },
  { title: "Guards! Guards!", author: "Terry Pratchett" },
  { title: "Half of a Yellow Sun", author: "Chimamanda Ngozi Adichie" },
  { title: "Hamnet", author: "Maggie O'Farrell" },
  { title: "Handle with Care", author: "Jodi Picoult" },
  { title: "Happy Place", author: "Emily Henry" },
  { title: "Hard-Boiled Wonderland and the End of the World", author: "Haruki Murakami" },
  { title: "Harlem Shuffle", author: "Colson Whitehead" },
  { title: "Harry Potter and the Chamber of Secrets", author: "J.K. Rowling" },
  { title: "Harry Potter and the Deathly Hallows", author: "J.K. Rowling" },
  { title: "Harry Potter and the Goblet of Fire", author: "J.K. Rowling" },
  { title: "Harry Potter and the Half-Blood Prince", author: "J.K. Rowling" },
  { title: "Harry Potter and the Order of the Phoenix", author: "J.K. Rowling" },
  { title: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling" },
  { title: "Harry Potter and the Prisoner of Azkaban", author: "J.K. Rowling" },
  { title: "Heir of Fire", author: "Sarah J. Maas" },
  { title: "Hello Beautiful", author: "Ann Napolitano" },
  { title: "His & Hers", author: "Alice Feeney" },
  { title: "Hold Tight", author: "Harlan Coben" },
  { title: "Holly", author: "Stephen King" },
  { title: "Home Before Dark", author: "Riley Sager" },
  { title: "Homecoming", author: "Kate Morton" },
  { title: "Homegoing", author: "Yaa Gyasi" },
  { title: "Hope to Die", author: "James Patterson" },
  { title: "House of Earth and Blood", author: "Sarah J. Maas" },
  { title: "House of Flame and Shadow", author: "Sarah J. Maas" },
  { title: "House of Leaves", author: "Mark Z. Danielewski" },
  { title: "House of Sky and Breath", author: "Sarah J. Maas" },
  { title: "How the King of Elfhame Learned to Hate Stories", author: "Holly Black" },
  { title: "How the Light Gets In", author: "Louise Penny" },
  { title: "Hyperion", author: "Dan Simmons" },
  { title: "I Will Find You", author: "Harlan Coben" },
  { title: "If It Bleeds", author: "Stephen King" },
  { title: "Ignite Me", author: "Tahereh Mafi" },
  { title: "Ikigai", author: "Héctor García & Francesc Miralles" },
  { title: "Imagine Me", author: "Tahereh Mafi" },
  { title: "In a Dark, Dark Wood", author: "Ruth Ware" },
  { title: "In the Woods", author: "Tana French" },
  { title: "Insurgent", author: "Veronica Roth" },
  { title: "Intensity", author: "Dean Koontz" },
  { title: "Invisible Girl", author: "Lisa Jewell" },
  { title: "Iron Flame", author: "Rebecca Yarros" },
  { title: "It", author: "Stephen King" },
  { title: "It Ends with Us", author: "Colleen Hoover" },
  { title: "It Starts with Us", author: "Colleen Hoover" },
  { title: "Jack & Jill", author: "James Patterson" },
  { title: "Jade City", author: "Fonda Lee" },
  { title: "Jade Legacy", author: "Fonda Lee" },
  { title: "Jade War", author: "Fonda Lee" },
  { title: "Jane Eyre", author: "Charlotte Brontë" },
  { title: "Journey Under the Midnight Sun", author: "Keigo Higashino" },
  { title: "Joyland", author: "Stephen King" },
  { title: "Just the Nicest Couple", author: "Mary Kubica" },
  { title: "Kafka on the Shore", author: "Haruki Murakami" },
  { title: "Killing Floor", author: "Lee Child" },
  { title: "King's Cage", author: "Victoria Aveyard" },
  { title: "Kingdom of Ash", author: "Sarah J. Maas" },
  { title: "Kingdom of the Blind", author: "Louise Penny" },
  { title: "Kiss the Girls", author: "James Patterson" },
  { title: "Klara and the Sun", author: "Kazuo Ishiguro" },
  { title: "Knife of Dreams", author: "Robert Jordan" },
  { title: "LaRose", author: "Louise Erdrich" },
  { title: "Last Argument of Kings", author: "Joe Abercrombie" },
  { title: "Last Man Standing", author: "David Baldacci" },
  { title: "Later", author: "Stephen King" },
  { title: "Leaving Time", author: "Jodi Picoult" },
  { title: "Legend", author: "Marie Lu" },
  { title: "Legendborn", author: "Tracy Deonn" },
  { title: "Legendary", author: "Stephanie Garber" },
  { title: "Les Misérables", author: "Victor Hugo" },
  { title: "Lethal White", author: "Robert Galbraith" },
  { title: "Life Expectancy", author: "Dean Koontz" },
  { title: "Life of Pi", author: "Yann Martel" },
  { title: "Lightning", author: "Dean Koontz" },
  { title: "Lincoln in the Bardo", author: "George Saunders" },
  { title: "Little Fires Everywhere", author: "Celeste Ng" },
  { title: "Little Women", author: "Louisa May Alcott" },
  { title: "Local Woman Missing", author: "Mary Kubica" },
  { title: "Lock Every Door", author: "Riley Sager" },
  { title: "Lone Wolf", author: "Jodi Picoult" },
  { title: "Long Road to Mercy", author: "David Baldacci" },
  { title: "Lord of Chaos", author: "Robert Jordan" },
  { title: "Love on the Brain", author: "Ali Hazelwood" },
  { title: "Mad Honey", author: "Jodi Picoult" },
  { title: "Mad Ship", author: "Robin Hobb" },
  { title: "Make Me", author: "Lee Child" },
  { title: "Malice", author: "Keigo Higashino" },
  { title: "Malibu Rising", author: "Taylor Jenkins Reid" },
  { title: "Man's Search for Meaning", author: "Viktor E. Frankl" },
  { title: "Maybe Someday", author: "Colleen Hoover" },
  { title: "Memory Man", author: "David Baldacci" },
  { title: "Mercy", author: "Jodi Picoult" },
  { title: "Mexican Gothic", author: "Silvia Moreno-Garcia" },
  { title: "Midnight", author: "Dean Koontz" },
  { title: "Misery", author: "Stephen King" },
  { title: "Missing You", author: "Harlan Coben" },
  { title: "Mistborn: The Final Empire", author: "Brandon Sanderson" },
  { title: "Moby-Dick", author: "Herman Melville" },
  { title: "Mockingjay", author: "Suzanne Collins" },
  { title: "Monstrous Regiment", author: "Terry Pratchett" },
  { title: "Moonlight Mile", author: "Dennis Lehane" },
  { title: "Mort", author: "Terry Pratchett" },
  { title: "Mr. Mercedes", author: "Stephen King" },
  { title: "Mrs. Everything", author: "Jennifer Weiner" },
  { title: "Murder on the Orient Express", author: "Agatha Christie" },
  { title: "My Sister's Keeper", author: "Jodi Picoult" },
  { title: "Mystic River", author: "Dennis Lehane" },
  { title: "Needful Things", author: "Stephen King" },
  { title: "Nemesis", author: "Agatha Christie" },
  { title: "Never Go Back", author: "Lee Child" },
  { title: "Never Let Me Go", author: "Kazuo Ishiguro" },
  { title: "Never Lie", author: "Freida McFadden" },
  { title: "Neverwhere", author: "Neil Gaiman" },
  { title: "Newcomer", author: "Keigo Higashino" },
  { title: "Nineteen Minutes", author: "Jodi Picoult" },
  { title: "No Country for Old Men", author: "Cormac McCarthy" },
  { title: "None of This Is True", author: "Lisa Jewell" },
  { title: "Norwegian Wood", author: "Haruki Murakami" },
  { title: "Nothing to Lose", author: "Lee Child" },
  { title: "November 9", author: "Colleen Hoover" },
  { title: "Oathbringer", author: "Brandon Sanderson" },
  { title: "Odd Thomas", author: "Dean Koontz" },
  { title: "Once Upon a Broken Heart", author: "Stephanie Garber" },
  { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
  { title: "One Shot", author: "Lee Child" },
  { title: "One by One", author: "Ruth Ware" },
  { title: "One of Us Is Lying", author: "Karen M. McManus" },
  { title: "One of Us Is Next", author: "Karen M. McManus" },
  { title: "Our Missing Hearts", author: "Celeste Ng" },
  { title: "Pachinko", author: "Min Jin Lee" },
  { title: "People We Meet on Vacation", author: "Emily Henry" },
  { title: "Peril at End House", author: "Agatha Christie" },
  { title: "Persuader", author: "Lee Child" },
  { title: "Persuasion", author: "Jane Austen" },
  { title: "Pet Sematary", author: "Stephen King" },
  { title: "Phantoms", author: "Dean Koontz" },
  { title: "Playing for Pizza", author: "John Grisham" },
  { title: "Prayers for Rain", author: "Dennis Lehane" },
  { title: "Pretty Baby", author: "Mary Kubica" },
  { title: "Pride and Prejudice", author: "Jane Austen" },
  { title: "Primeval and Other Times", author: "Olga Tokarczuk" },
  { title: "Prodigy", author: "Marie Lu" },
  { title: "Project Hail Mary", author: "Andy Weir" },
  { title: "Purple Hibiscus", author: "Chimamanda Ngozi Adichie" },
  { title: "Queen of Shadows", author: "Sarah J. Maas" },
  { title: "Ready Player One", author: "Ernest Cline" },
  { title: "Reaper Man", author: "Terry Pratchett" },
  { title: "Rebecca", author: "Daphne du Maurier" },
  { title: "Reckless Girls", author: "Rachel Hawkins" },
  { title: "Red Country", author: "Joe Abercrombie" },
  { title: "Red Queen", author: "Victoria Aveyard" },
  { title: "Red Seas Under Red Skies", author: "Scott Lynch" },
  { title: "Remarkably Bright Creatures", author: "Shelby Van Pelt" },
  { title: "Reminders of Him", author: "Colleen Hoover" },
  { title: "Restore Me", author: "Tahereh Mafi" },
  { title: "Resurrection Walk", author: "Michael Connelly" },
  { title: "Revival", author: "Stephen King" },
  { title: "Rhythm of War", author: "Brandon Sanderson" },
  { title: "Rich Dad Poor Dad", author: "Robert T. Kiyosaki" },
  { title: "River of Smoke", author: "Amitav Ghosh" },
  { title: "Rock Paper Scissors", author: "Alice Feeney" },
  { title: "Rogue Lawyer", author: "John Grisham" },
  { title: "Roses Are Red", author: "James Patterson" },
  { title: "Royal Assassin", author: "Robin Hobb" },
  { title: "Ruin and Rising", author: "Leigh Bardugo" },
  { title: "Run Away", author: "Harlan Coben" },
  { title: "Run, Rose, Run", author: "James Patterson & Dolly Parton" },
  { title: "Salem's Lot", author: "Stephen King" },
  { title: "Sapiens", author: "Yuval Noah Harari" },
  { title: "Scythe", author: "Neal Shusterman" },
  { title: "Sea of Poppies", author: "Amitav Ghosh" },
  { title: "Sea of Tranquility", author: "Emily St. John Mandel" },
  { title: "Sense and Sensibility", author: "Jane Austen" },
  { title: "Shadow and Bone", author: "Leigh Bardugo" },
  { title: "Shantaram", author: "Gregory David Roberts" },
  { title: "Shards of Earth", author: "Adrian Tchaikovsky" },
  { title: "Sharp Objects", author: "Gillian Flynn" },
  { title: "Shatter Me", author: "Tahereh Mafi" },
  { title: "She's Not Sorry", author: "Mary Kubica" },
  { title: "Ship of Destiny", author: "Robin Hobb" },
  { title: "Ship of Magic", author: "Robin Hobb" },
  { title: "Shutter Island", author: "Dennis Lehane" },
  { title: "Siege and Storm", author: "Leigh Bardugo" },
  { title: "Six Years", author: "Harlan Coben" },
  { title: "Six of Crows", author: "Leigh Bardugo" },
  { title: "Skipping Christmas", author: "John Grisham" },
  { title: "Sleeping Murder", author: "Agatha Christie" },
  { title: "Small Gods", author: "Terry Pratchett" },
  { title: "Small Great Things", author: "Jodi Picoult" },
  { title: "Sometimes I Lie", author: "Alice Feeney" },
  { title: "South of the Border, West of the Sun", author: "Haruki Murakami" },
  { title: "Stardust", author: "Neil Gaiman" },
  { title: "Station Eleven", author: "Emily St. John Mandel" },
  { title: "Stay Awake", author: "Megan Goldin" },
  { title: "Stay Close", author: "Harlan Coben" },
  { title: "Still Life", author: "Louise Penny" },
  { title: "Stone Cold", author: "David Baldacci" },
  { title: "Summer of Night", author: "Dan Simmons" },
  { title: "Survive the Night", author: "Riley Sager" },
  { title: "Sweet Bean Paste", author: "Durian Sukegawa" },
  { title: "Sycamore Row", author: "John Grisham" },
  { title: "Tales from the Cafe", author: "Toshikazu Kawaguchi" },
  { title: "Tell No One", author: "Harlan Coben" },
  { title: "Tenth of December", author: "George Saunders" },
  { title: "That Summer", author: "Jennifer Weiner" },
  { title: "The ABC Murders", author: "Agatha Christie" },
  { title: "The Alchemist", author: "Paulo Coelho" },
  { title: "The Alice Network", author: "Kate Quinn" },
  { title: "The Amazing Adventures of Kavalier & Clay", author: "Michael Chabon" },
  { title: "The Angel's Game", author: "Carlos Ruiz Zafón" },
  { title: "The Appeal", author: "John Grisham" },
  { title: "The Assassin's Apprentice", author: "Robin Hobb" },
  { title: "The Associate", author: "John Grisham" },
  { title: "The Atlas Six", author: "Olivie Blake" },
  { title: "The Bastard of Istanbul", author: "Elif Shafak" },
  { title: "The Bee Sting", author: "Paul Murray" },
  { title: "The Black Echo", author: "Michael Connelly" },
  { title: "The Black Ice", author: "Michael Connelly" },
  { title: "The Blade Itself", author: "Joe Abercrombie" },
  { title: "The Bone Season", author: "Samantha Shannon" },
  { title: "The Book Thief", author: "Markus Zusak" },
  { title: "The Book of Longings", author: "Sue Monk Kidd" },
  { title: "The Brass Verdict", author: "Michael Connelly" },
  { title: "The Breakaway", author: "Jennifer Weiner" },
  { title: "The Breakdown", author: "B. A. Paris" },
  { title: "The Brethren", author: "John Grisham" },
  { title: "The Brothers Hawthorne", author: "Jennifer Lynn Barnes" },
  { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky" },
  { title: "The Bullet That Missed", author: "Richard Osman" },
  { title: "The Burning God", author: "R. F. Kuang" },
  { title: "The Camel Club", author: "David Baldacci" },
  { title: "The Catcher in the Rye", author: "J.D. Salinger" },
  { title: "The Chamber", author: "John Grisham" },
  { title: "The Christmas Train", author: "David Baldacci" },
  { title: "The Chronicles of Narnia", author: "C.S. Lewis" },
  { title: "The Client", author: "John Grisham" },
  { title: "The Clockmaker's Daughter", author: "Kate Morton" },
  { title: "The Colour of Magic", author: "Terry Pratchett" },
  { title: "The Concrete Blonde", author: "Michael Connelly" },
  { title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
  { title: "The Coworker", author: "Freida McFadden" },
  { title: "The Crossing", author: "Michael Connelly" },
  { title: "The Cruel Prince", author: "Holly Black" },
  { title: "The Cruelest Month", author: "Louise Penny" },
  { title: "The Cuckoo's Calling", author: "Robert Galbraith" },
  { title: "The Da Vinci Code", author: "Dan Brown" },
  { title: "The Death of Mrs. Westaway", author: "Ruth Ware" },
  { title: "The Devotion of Suspect X", author: "Keigo Higashino" },
  { title: "The Dilemma", author: "B. A. Paris" },
  { title: "The Distant Hours", author: "Kate Morton" },
  { title: "The Dragon Reborn", author: "Robert Jordan" },
  { title: "The Dragon Republic", author: "R. F. Kuang" },
  { title: "The Dream Thieves", author: "Maggie Stiefvater" },
  { title: "The Dry", author: "Jane Harper" },
  { title: "The Dutch House", author: "Ann Patchett" },
  { title: "The Dutch Wife", author: "Ellen Keith" },
  { title: "The Elite", author: "Kiera Cass" },
  { title: "The Enemy", author: "Lee Child" },
  { title: "The Escape Room", author: "Megan Goldin" },
  { title: "The Eye of the World", author: "Robert Jordan" },
  { title: "The Face", author: "Dean Koontz" },
  { title: "The Fall of Hyperion", author: "Dan Simmons" },
  { title: "The Family Upstairs", author: "Lisa Jewell" },
  { title: "The Fault in Our Stars", author: "John Green" },
  { title: "The Fifth Season", author: "N. K. Jemisin" },
  { title: "The Final Empire", author: "Brandon Sanderson" },
  { title: "The Final Gambit", author: "Jennifer Lynn Barnes" },
  { title: "The Fires of Heaven", author: "Robert Jordan" },
  { title: "The Firm", author: "John Grisham" },
  { title: "The Forest of Enchantments", author: "Chitra Banerjee Divakaruni" },
  { title: "The Forgotten Garden", author: "Kate Morton" },
  { title: "The Four Winds", author: "Kristin Hannah" },
  { title: "The Fury", author: "Alex Michaelides" },
  { title: "The Gathering Storm", author: "Robert Jordan & Brandon Sanderson" },
  { title: "The Girl Who Kicked the Hornet's Nest", author: "Stieg Larsson" },
  { title: "The Girl Who Played with Fire", author: "Stieg Larsson" },
  { title: "The Girl on the Train", author: "Paula Hawkins" },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson" },
  { title: "The Giver", author: "Lois Lowry" },
  { title: "The Glass Palace", author: "Amitav Ghosh" },
  { title: "The Goldfinch", author: "Donna Tartt" },
  { title: "The Good Girl", author: "Mary Kubica" },
  { title: "The Good Sister", author: "Sally Hepworth" },
  { title: "The Great Alone", author: "Kristin Hannah" },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
  { title: "The Great Hunt", author: "Robert Jordan" },
  { title: "The Green Mile", author: "Stephen King" },
  { title: "The Guest List", author: "Lucy Foley" },
  { title: "The Hawthorne Legacy", author: "Jennifer Lynn Barnes" },
  { title: "The Hero of Ages", author: "Brandon Sanderson" },
  { title: "The Heroes", author: "Joe Abercrombie" },
  { title: "The Historian", author: "Elizabeth Kostova" },
  { title: "The Hobbit", author: "J.R.R. Tolkien" },
  { title: "The Honjin Murders", author: "Seishi Yokomizo" },
  { title: "The House in the Cerulean Sea", author: "T. J. Klune" },
  { title: "The House of the Spirits", author: "Isabel Allende" },
  { title: "The Housemaid", author: "Freida McFadden" },
  { title: "The Housemaid Is Watching", author: "Freida McFadden" },
  { title: "The Housemaid's Secret", author: "Freida McFadden" },
  { title: "The Humans", author: "Matt Haig" },
  { title: "The Hunger Games", author: "Suzanne Collins" },
  { title: "The Hunter", author: "Tana French" },
  { title: "The Hunting Party", author: "Lucy Foley" },
  { title: "The Huntress", author: "Kate Quinn" },
  { title: "The Husband", author: "Dean Koontz" },
  { title: "The Iliad", author: "Homer" },
  { title: "The Inheritance Games", author: "Jennifer Lynn Barnes" },
  { title: "The Ink Black Heart", author: "Robert Galbraith" },
  { title: "The Innocent", author: "Harlan Coben" },
  { title: "The Institute", author: "Stephen King" },
  { title: "The Inugami Curse", author: "Seishi Yokomizo" },
  { title: "The Invention of Wings", author: "Sue Monk Kidd" },
  { title: "The Invisible Bridge", author: "Julie Orringer" },
  { title: "The Invisible Life of Addie LaRue", author: "V. E. Schwab" },
  { title: "The Island of Missing Trees", author: "Elif Shafak" },
  { title: "The Kite Runner", author: "Khaled Hosseini" },
  { title: "The Labyrinth of the Spirits", author: "Carlos Ruiz Zafón" },
  { title: "The Lake House", author: "Kate Morton" },
  { title: "The Last Devil to Die", author: "Richard Osman" },
  { title: "The Last House Guest", author: "Megan Miranda" },
  { title: "The Last Mrs. Parrish", author: "Liv Constantine" },
  { title: "The Last Queen", author: "Chitra Banerjee Divakaruni" },
  { title: "The Last Thing He Told Me", author: "Laura Dave" },
  { title: "The Last Time I Lied", author: "Riley Sager" },
  { title: "The Lies of Locke Lamora", author: "Scott Lynch" },
  { title: "The Light Fantastic", author: "Terry Pratchett" },
  { title: "The Likeness", author: "Tana French" },
  { title: "The Lincoln Highway", author: "Amor Towles" },
  { title: "The Lincoln Lawyer", author: "Michael Connelly" },
  { title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis" },
  { title: "The Litigators", author: "John Grisham" },
  { title: "The Locked Door", author: "Freida McFadden" },
  { title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
  { title: "The Lost Man", author: "Jane Harper" },
  { title: "The Love Hypothesis", author: "Ali Hazelwood" },
  { title: "The Madness of Crowds", author: "Louise Penny" },
  { title: "The Maid", author: "Nita Prose" },
  { title: "The Maid's Secret", author: "Nita Prose" },
  { title: "The Maidens", author: "Alex Michaelides" },
  { title: "The Man Who Died Twice", author: "Richard Osman" },
  { title: "The Marriage Portrait", author: "Maggie O'Farrell" },
  { title: "The Martian", author: "Andy Weir" },
  { title: "The Memory Police", author: "Yoko Ogawa" },
  { title: "The Mermaid Chair", author: "Sue Monk Kidd" },
  { title: "The Midnight Feast", author: "Lucy Foley" },
  { title: "The Midnight Library", author: "Matt Haig" },
  { title: "The Miracles of the Namiya General Store", author: "Keigo Higashino" },
  { title: "The Mother-in-Law", author: "Sally Hepworth" },
  { title: "The Mothers", author: "Brit Bennett" },
  { title: "The Mountains Sing", author: "Nguyễn Phan Quế Mai" },
  { title: "The Murder of Roger Ackroyd", author: "Agatha Christie" },
  { title: "The Mysterious Affair at Styles", author: "Agatha Christie" },
  { title: "The Name of the Wind", author: "Patrick Rothfuss" },
  { title: "The Nature of the Beast", author: "Louise Penny" },
  { title: "The Nickel Boys", author: "Colson Whitehead" },
  { title: "The Night Circus", author: "Erin Morgenstern" },
  { title: "The Night She Disappeared", author: "Lisa Jewell" },
  { title: "The Night Swim", author: "Megan Goldin" },
  { title: "The Night Watchman", author: "Louise Erdrich" },
  { title: "The Nightingale", author: "Kristin Hannah" },
  { title: "The Obelisk Gate", author: "N. K. Jemisin" },
  { title: "The Odyssey", author: "Homer" },
  { title: "The Old Man and the Sea", author: "Ernest Hemingway" },
  { title: "The One", author: "Kiera Cass" },
  { title: "The Only One Left", author: "Riley Sager" },
  { title: "The Outsider", author: "Stephen King" },
  { title: "The Overstory", author: "Richard Powers" },
  { title: "The Pact", author: "Jodi Picoult" },
  { title: "The Palace of Illusions", author: "Chitra Banerjee Divakaruni" },
  { title: "The Paper Palace", author: "Miranda Cowley Heller" },
  { title: "The Paris Apartment", author: "Lucy Foley" },
  { title: "The Paris Library", author: "Janet Skeslien Charles" },
  { title: "The Paris Widow", author: "Kimberly Belle" },
  { title: "The Path of Daggers", author: "Robert Jordan" },
  { title: "The Pelican Brief", author: "John Grisham" },
  { title: "The Personal Assistant", author: "Kimberly Belle" },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
  { title: "The Poet", author: "Michael Connelly" },
  { title: "The Poisonwood Bible", author: "Barbara Kingsolver" },
  { title: "The Poppy War", author: "R. F. Kuang" },
  { title: "The Power of Now", author: "Eckhart Tolle" },
  { title: "The Priory of the Orange Tree", author: "Samantha Shannon" },
  { title: "The Prisoner", author: "B. A. Paris" },
  { title: "The Prisoner of Heaven", author: "Carlos Ruiz Zafón" },
  { title: "The Prisoner's Throne", author: "Holly Black" },
  { title: "The Psychology of Money", author: "Morgan Housel" },
  { title: "The Queen of Nothing", author: "Holly Black" },
  { title: "The Raven Boys", author: "Maggie Stiefvater" },
  { title: "The Raven King", author: "Maggie Stiefvater" },
  { title: "The Reappearance of Rachel Price", author: "Holly Jackson" },
  { title: "The Reckoning", author: "John Grisham" },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro" },
  { title: "The Republic of Thieves", author: "Scott Lynch" },
  { title: "The Reversal", author: "Michael Connelly" },
  { title: "The Road", author: "Cormac McCarthy" },
  { title: "The Rose Code", author: "Kate Quinn" },
  { title: "The Runaway Jury", author: "John Grisham" },
  { title: "The Running Grave", author: "Robert Galbraith" },
  { title: "The Searcher", author: "Tana French" },
  { title: "The Secret Garden", author: "Frances Hodgson Burnett" },
  { title: "The Secret History", author: "Donna Tartt" },
  { title: "The Secret Keeper", author: "Kate Morton" },
  { title: "The Secret Place", author: "Tana French" },
  { title: "The Selection", author: "Kiera Cass" },
  { title: "The Senator's Wife", author: "Liv Constantine" },
  { title: "The Sentence", author: "Louise Erdrich" },
  { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid" },
  { title: "The Shadow Rising", author: "Robert Jordan" },
  { title: "The Shadow of the Wind", author: "Carlos Ruiz Zafón" },
  { title: "The Shining", author: "Stephen King" },
  { title: "The Silent Corner", author: "Dean Koontz" },
  { title: "The Silent Patient", author: "Alex Michaelides" },
  { title: "The Silent Wife", author: "A. S. A. Harrison" },
  { title: "The Silkworm", author: "Robert Galbraith" },
  { title: "The Slow Regard of Silent Things", author: "Patrick Rothfuss" },
  { title: "The Song of Achilles", author: "Madeline Miller" },
  { title: "The Soulmate", author: "Sally Hepworth" },
  { title: "The Stand", author: "Stephen King" },
  { title: "The Stolen Heir", author: "Holly Black" },
  { title: "The Stone Sky", author: "N. K. Jemisin" },
  { title: "The Stranger", author: "Harlan Coben" },
  { title: "The Stranger in the Mirror", author: "Liv Constantine" },
  { title: "The Street Lawyer", author: "John Grisham" },
  { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson" },
  { title: "The Sunlit Man", author: "Brandon Sanderson" },
  { title: "The Taking", author: "Dean Koontz" },
  { title: "The Teacher", author: "Freida McFadden" },
  { title: "The Terror", author: "Dan Simmons" },
  { title: "The Testament", author: "John Grisham" },
  { title: "The Therapist", author: "B. A. Paris" },
  { title: "The Thirteenth Tale", author: "Diane Setterfield" },
  { title: "The Thursday Murder Club", author: "Richard Osman" },
  { title: "The Toll", author: "Neal Shusterman" },
  { title: "The Travelling Cat Chronicles", author: "Hiro Arikawa" },
  { title: "The Truth", author: "Terry Pratchett" },
  { title: "The Turn of the Key", author: "Ruth Ware" },
  { title: "The Underground Railroad", author: "Colson Whitehead" },
  { title: "The Vanishing Half", author: "Brit Bennett" },
  { title: "The Villa", author: "Rachel Hawkins" },
  { title: "The Way of Kings", author: "Brandon Sanderson" },
  { title: "The Well of Ascension", author: "Brandon Sanderson" },
  { title: "The Whistler", author: "John Grisham" },
  { title: "The White Tiger", author: "Aravind Adiga" },
  { title: "The Wicked King", author: "Holly Black" },
  { title: "The Wife Upstairs", author: "Rachel Hawkins" },
  { title: "The Wind-Up Bird Chronicle", author: "Haruki Murakami" },
  { title: "The Winner", author: "David Baldacci" },
  { title: "The Wise Man's Fear", author: "Patrick Rothfuss" },
  { title: "The Woman in Cabin 10", author: "Ruth Ware" },
  { title: "The Woods", author: "Harlan Coben" },
  { title: "The Yiddish Policemen's Union", author: "Michael Chabon" },
  { title: "The Younger Wife", author: "Sally Hepworth" },
  { title: "Then She Was Gone", author: "Lisa Jewell" },
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman" },
  { title: "Throne of Glass", author: "Sarah J. Maas" },
  { title: "Thunderhead", author: "Neal Shusterman" },
  { title: "Tick Tock", author: "Dean Koontz" },
  { title: "To Kill a Mockingbird", author: "Harper Lee" },
  { title: "Tomorrow, and Tomorrow, and Tomorrow", author: "Gabrielle Zevin" },
  { title: "Tower of Dawn", author: "Sarah J. Maas" },
  { title: "Towers of Midnight", author: "Robert Jordan & Brandon Sanderson" },
  { title: "Transcendent Kingdom", author: "Yaa Gyasi" },
  { title: "Tress of the Emerald Sea", author: "Brandon Sanderson" },
  { title: "Tripwire", author: "Lee Child" },
  { title: "Troubled Blood", author: "Robert Galbraith" },
  { title: "Two Can Keep a Secret", author: "Karen M. McManus" },
  { title: "Ugly Love", author: "Colleen Hoover" },
  { title: "Under the Dome", author: "Stephen King" },
  { title: "Under the Whispering Door", author: "T. J. Klune" },
  { title: "Unravel Me", author: "Tahereh Mafi" },
  { title: "Velocity", author: "Dean Koontz" },
  { title: "Verity", author: "Colleen Hoover" },
  { title: "Vicious", author: "V. E. Schwab" },
  { title: "Violets Are Blue", author: "James Patterson" },
  { title: "War Storm", author: "Victoria Aveyard" },
  { title: "War and Peace", author: "Leo Tolstoy" },
  { title: "Warbreaker", author: "Brandon Sanderson" },
  { title: "Ward D", author: "Freida McFadden" },
  { title: "Watching You", author: "Lisa Jewell" },
  { title: "Watchers", author: "Dean Koontz" },
  { title: "Where the Crawdads Sing", author: "Delia Owens" },
  { title: "Win", author: "Harlan Coben" },
  { title: "Winter's Heart", author: "Robert Jordan" },
  { title: "Wish You Well", author: "David Baldacci" },
  { title: "Wish You Were Here", author: "Jodi Picoult" },
  { title: "Without Fail", author: "Lee Child" },
  { title: "Words of Radiance", author: "Brandon Sanderson" },
  { title: "Worth Dying For", author: "Lee Child" },
  { title: "Wuthering Heights", author: "Emily Brontë" },
  { title: "Yellowface", author: "R. F. Kuang" },
  { title: "You'll Be the Death of Me", author: "Karen M. McManus" },
  { title: "Yumi and the Nightmare Painter", author: "Brandon Sanderson" },
  { title: "Zero Day", author: "David Baldacci" },
  { title: "Zero Days", author: "Ruth Ware" },
];
